site_name: "Vélib’ Paris — Forecast +15min (Batch)"
site_url: "https://adrien-1997.github.io/bike-forecast-paris-velib/"
repo_url: "https://github.com/Adrien-1997/bike-forecast-paris-velib"
repo_name: "Adrien-1997/bike-forecast-paris-velib"

theme:
  name: material
  language: fr
  features:
    - navigation.expand
    - navigation.top
    - navigation.tracking
    - toc.follow
    - content.code.copy
    - content.tabs.link
    - search.highlight
    - search.suggest
    - search.share
  icon:
    repo: fontawesome/brands/github
  palette:
    - scheme: default
      primary: blue
      accent: light blue

extra_css:
  - assets/extra.css

plugins:
  - search

markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - md_in_html
  - tables
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.mark
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - Accueil: index.md

  - Réseau:
      - Index: network/index.md
      - Aperçu du réseau: network/overview.md
      - Stations & profils: network/stations.md
      - Dynamiques spatio-temporelles: network/dynamics.md

  - Modèle:
      - Index: model/index.md
      - Performance & baseline: model/performance.md
      - Pipeline d’entraînement & features: model/pipeline.md
      - Explicabilité & calibration: model/explainability.md

  - Monitoring:
      - Index: monitoring/index.md
      - Santé des données: monitoring/data-health.md
      - Drift des données: monitoring/drift.md
      - Santé du modèle: monitoring/model-health.md

  - Données:
      - Index: data/index.md
      - Exports: data/exports.md
      - Dictionnaire & schéma: data/dictionary.md
      - Méthodologie & licences: data/methodology.md
