site_name: Vélib’ Paris — Forecast (Batch)
site_url: https://adrien-1997.github.io/bike-forecast-paris-velib/
repo_url: https://github.com/Adrien-1997/bike-forecast-paris-velib
repo_name: Adrien-1997/bike-forecast-paris-velib

theme:
  name: material
  language: fr
  features:
    - navigation.expand
    - navigation.top
    - navigation.tracking
    - toc.follow
    - content.code.copy
    - content.tabs.link
    - search.highlight
    - search.suggest
    - search.share
  icon:
    repo: fontawesome/brands/github
  palette:
    - scheme: default
      primary: blue
      accent: light blue

extra_css:
  - assets/extra.css

plugins:
  - search

markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - md_in_html
  - tables
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.mark
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - Accueil: index.md
  - Projet:
      - Rapport complet: project/report.md
      - Architecture: project/architecture.md
  - Monitoring:
      - Vue d’ensemble: monitoring/index.md
      - Métriques: monitoring/metrics.md
      - Drift: monitoring/data_drift.md
      - Modèle: monitoring/model.md
  - Exports: exports/index.md
