options:
  substitutionOption: ALLOW_LOOSE
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: gcr.io/cloud-builders/docker
    id: docker-build
    dir: apps/api
    args: ['build', '-t', '$_IMAGE_URI', '-f', 'Dockerfile', '.']

  - name: gcr.io/cloud-builders/docker
    id: docker-push
    args: ['push', '$_IMAGE_URI']

images:
  - '$_IMAGE_URI'
