# =============================================================================
#  Vélib’ Forecast — Cloud Build Pipeline (final)
# =============================================================================
#  Build + Deploy all Cloud Run Jobs and update the monitoring chain.
# =============================================================================

substitutions:
  _REGION:   "europe-west1"
  _AR_PATH:  "europe-west1-docker.pkg.dev/velib-forecast-472820/velib-docker/pipeline"

  # GCS paths
  _RAW:      "gs://velib-forecast-472820_cloudbuild/velib/bronze"
  _DAILY:    "gs://velib-forecast-472820_cloudbuild/velib/daily"
  _SERVING:  "gs://velib-forecast-472820_cloudbuild/velib/serving"
  _EXPORTS:  "gs://velib-forecast-472820_cloudbuild/velib/exports"
  _MODELS:   "gs://velib-forecast-472820_cloudbuild/velib/models"
  _MON:      "gs://velib-forecast-472820_cloudbuild/velib/monitoring"

# =============================================================================
#  BUILD & PUSH IMAGE (depuis la racine)
# =============================================================================
steps:
- name: gcr.io/cloud-builders/docker
  args:
    - build
    - -f
    - service/Dockerfile          # Dockerfile dans service/
    - -t
    - ${_AR_PATH}:$BUILD_ID
    - .                           # ⬅️ Contexte de build = racine du projet (IMPORTANT)
  id: build-image

- name: gcr.io/cloud-builders/docker
  args:
    - push
    - ${_AR_PATH}:$BUILD_ID
  id: push-image

# =============================================================================
#  PARQUET-FIRST JOBS
# =============================================================================

# 1️⃣ Ingest
- name: gcr.io/cloud-builders/gcloud
  args:
    - run
    - jobs
    - update
    - velib-ingest
    - --region
    - ${_REGION}
    - --image
    - ${_AR_PATH}:$BUILD_ID
    - --command=python
    - --args=-m,core.utils_gcs
    - --update-env-vars
    - JOB=ingest,GCS_RAW_PREFIX=${_RAW}
  id: job-ingest

# 2️⃣ Compact daily
- name: gcr.io/cloud-builders/gcloud
  args:
    - run
    - jobs
    - update
    - velib-compact-daily
    - --region
    - ${_REGION}
    - --image
    - ${_AR_PATH}:$BUILD_ID
    - --command=python
    - --args=-m,core.utils_gcs
    - --update-env-vars
    - JOB=compact_daily,GCS_RAW_PREFIX=${_RAW},GCS_DAILY_PREFIX=${_DAILY}
  id: job-compact-daily

# 3️⃣ Serving forecast
- name: gcr.io/cloud-builders/gcloud
  args:
    - run
    - jobs
    - update
    - velib-serving-forecast
    - --region
    - ${_REGION}
    - --image
    - ${_AR_PATH}:$BUILD_ID
    - --command=python
    - --args=-m,core.utils_gcs
    - --update-env-vars=^~^
    - >
      JOB=build_serving_forecast
      ~ GCS_RAW_PREFIX=${_RAW}
      ~ SERVING_FORECAST_PREFIX=${_SERVING}/forecast
      ~ GCS_MODEL_URI_T15=${_MODELS}/h15/latest.joblib
      ~ GCS_MODEL_URI_T60=${_MODELS}/h60/latest.joblib
      ~ FORECAST_HORIZONS=15,60
      ~ WINDOW_HOURS=4
      ~ WITH_FORECAST=1
  id: job-serving-forecast

# 4️⃣ Compact monthly
- name: gcr.io/cloud-builders/gcloud
  args:
    - run
    - jobs
    - update
    - velib-compact-monthly
    - --region
    - ${_REGION}
    - --image
    - ${_AR_PATH}:$BUILD_ID
    - --command=python
    - --args=-m,core.utils_gcs
    - --update-env-vars
    - JOB=compact_monthly,GCS_DAILY_PREFIX=${_DAILY},GCS_SERVING_PREFIX=${_SERVING}/monthly,DELETE_DAILIES=1
  id: job-compact-monthly

# =============================================================================
#  MONITORING PIPELINE (v2)
# =============================================================================

# 5️⃣ Unified monitoring pipeline
- name: gcr.io/cloud-builders/gcloud
  args:
    - run
    - jobs
    - update
    - velib-monitoring
    - --region
    - ${_REGION}
    - --image
    - ${_AR_PATH}:$BUILD_ID
    - --command=python
    - --args=-m,core.utils_gcs
    - --update-env-vars=^~^
    - >
      JOB=monitoring_pipeline
      ~ GCS_EXPORTS_PREFIX=${_EXPORTS}
      ~ GCS_MONITORING_PREFIX=${_MON}
      ~ FORECAST_HORIZONS=15,60
      ~ MODEL_URI_15=${_MODELS}/h15/latest.joblib
      ~ MODEL_URI_60=${_MODELS}/h60/latest.joblib
      ~ TZ_APP=Europe/Paris
      ~ OVERVIEW_LAST_DAYS=28
      ~ DYNAMICS_LAST_DAYS=14
      ~ NETWORK_WINDOW_DAYS=14
      ~ PERF_LAST_DAYS=14
      ~ LOOKBACK_DAYS=14
      ~ MON_LAST_DAYS=14
      ~ MON_REF_DAYS=28
  id: job-monitoring

# =============================================================================
#  IMAGE REGISTRY
# =============================================================================
images:
  - ${_AR_PATH}:$BUILD_ID
