name: gh-pages

on:
  # 1) se lance quand "pipeline-velib" termine (succès)
  workflow_run:
    workflows: ["pipeline-velib"]
    types: [completed]

  # 2) toujours possible à la main
  workflow_dispatch:

  # 3) (optionnel) sur push direct — on évite le double build avec un guard plus bas
  push:
    branches: [ main ]
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
      - 'tools/**'
      - 'src/**'
      - 'exports/**'
      - '.github/workflows/gh-pages.yml'

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-deploy:
    # si déclenché par workflow_run, ne tourner que si le pipeline est "success"
    if: >
      github.event_name != 'workflow_run' ||
      github.event.workflow_run.conclusion == 'success'

    # éviter les doublons quand ce workflow est déclenché par un "push" fait par le bot
    # (le pipeline-velib commit & push) : on skip dans ce cas
    # -> retire cette ligne si tu veux aussi builder sur ces push.
    if: >
      (github.event_name != 'push') ||
      (github.event_name == 'push' && github.actor != 'github-actions[bot]')

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo at the right revision
        uses: actions/checkout@v4
        with:
          # si on vient de workflow_run, on reconstruit exactement sur le commit du pipeline
          ref: ${{ github.event_name == 'workflow_run' && github.event.workflow_run.head_sha || github.sha }}
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt || true
          pip install mkdocs-material mkdocs-jupyter matplotlib pyarrow pandas duckdb lightgbm holidays tabulate folium joblib

      - name: Generate pages (map, history, forecast)
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: |
          python tools/make_map.py
          python tools/make_report.py
          python tools/make_forecast_page.py

      - name: Build site
        run: mkdocs build --strict

      - name: Publish to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
