name: velib-ingest

on:
  schedule:
    # Quarts d’heure précis en UTC → 01,16,31,46
    - cron: "1,16,31,46 * * * *"
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: velib-ingest
  cancel-in-progress: true

jobs:
  ingest_aggregate:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install pipeline deps
        run: |
          python -m pip install -U pip
          pip install -r requirements-pipeline.txt

      - name: Ingest snapshot (OpenData → DuckDB)
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: python -m src.ingest

      - name: Aggregate 15min + weather → docs/exports/
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: python -m src.aggregate

      - name: Commit data if changed
        run: |
          set -euxo pipefail
          git config user.name  "github-actions"
          git config user.email "actions@users.noreply.github.com"
          git add docs/exports/*.parquet docs/exports/*.csv warehouse.duckdb || true
          if git diff --cached --quiet; then
            echo "Nothing to commit."
          else
            git commit -m "ci(ingest): update 15min data"
            git push
          fi
