name: pipeline-velib
on:
  schedule: [{ cron: "*/15 * * * *" }]
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }

      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt
          pip install mkdocs-material mkdocs-jupyter matplotlib pyarrow

      - name: Ingest snapshot (Velib)
        run: python -m src.ingest

      - name: Prune warehouse (>30 days) to keep repo light
        run: |
          python - << 'PY'
          import duckdb, datetime as dt
          con = duckdb.connect("warehouse.duckdb")
          cutoff = (dt.datetime.utcnow() - dt.timedelta(days=30)).date()
          con.execute("DELETE FROM velib_snapshots WHERE ts_utc::DATE < ?", [cutoff])
          print("Pruned rows before", cutoff)
          PY

      - name: Aggregate hourly + forecast 24h
        run: |
          python -m src.aggregate
          python -m src.run_batch

      - name: Generate docs (Results page)
        run: python tools/make_report.py

      - name: Build site
        run: mkdocs build

      - name: Commit exports, docs, and warehouse
        run: |
          git config user.name "github-actions"
          git config user.email "actions@users.noreply.github.com"
          git add exports docs warehouse.duckdb || true
          git commit -m "ci: +snapshot, +hourly, +forecast, +docs" || echo "nothing to commit"
          git push

      - name: Publish to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
