name: pipeline-velib
on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt
          pip install mkdocs-material pymdown-extensions duckdb pandas pyarrow matplotlib lightgbm holidays folium

      - name: Ingest snapshot (retry x3)
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: |
          set -e
          for i in 1 2 3; do
            python -m src.ingest && break || (echo "retry $i/3" && sleep 5)
          done

      - name: Aggregate hourly + weather
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: python -m src.aggregate

      - name: Generate docs (map, KPI, history, forecast)
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: |
          python tools/make_map.py
          python tools/make_kpi_banner.py
          python tools/make_report.py
          python tools/make_forecast_page.py

      - name: Build site (sanity check)
        run: mkdocs build --strict

      - name: Commit data & docs if changed
        run: |
          set -euxo pipefail
          git config user.name  "github-actions"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          if git diff --cached --quiet; then
            echo "Nothing to commit."
            exit 0
          fi
          git commit -m "ci: update hourly data and docs"
          git push