name: velib-train

on:
  schedule:
    # Entraînement quotidien à 02:17 UTC
    - cron: "17 2 * * *"
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: velib-train
  cancel-in-progress: true

jobs:
  train_daily:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install training deps
        run: |
          python -m pip install -U pip
          pip install -r requirements-train.txt

      - name: Check dataset presence
        run: |
          if [ ! -f docs/exports/velib.parquet ] && [ ! -f warehouse.duckdb ]; then
            echo "Dataset manquant (docs/exports/velib.parquet ou warehouse.duckdb requis)"; exit 1;
          fi
          ls -lh docs/exports || true

      - name: Train LightGBM (T+60min, pas 15 min)
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: python -c "from src.forecast import train; train(horizon_minutes=60, lookback_days=30)"

      - name: Upload model bundle
        uses: actions/upload-artifact@v4
        with:
          name: model-lgbm-T+60min
          path: models/lgb_nbvelos_T+60min.joblib
          retention-days: 14

      # (Optionnel) Commit du modèle dans le repo
      # - name: Commit model if changed
      #   run: |
      #     set -euxo pipefail
      #     git config user.name  "github-actions"
      #     git config user.email "actions@users.noreply.github.com"
      #     git add models/lgb_nbvelos_T+60min.joblib || true
      #     if git diff --cached --quiet; then
      #       echo "Nothing to commit."
      #     else
      #       git commit -m "ci(train): update LGBM model T+60min"
      #       git push
      #     fi
