name: velib-train

on:
  schedule:
    # Entraînement quotidien à 02:17 UTC
    - cron: "17 2 * * *"
  workflow_dispatch:
  # (Optionnel) déclencher après l’ingest si tu veux enchaîner automatiquement
  # workflow_run:
  #   workflows: ["velib-ingest"]
  #   types: [completed]

permissions:
  contents: write

concurrency:
  group: velib-train
  cancel-in-progress: true

jobs:
  train_daily:
    runs-on: ubuntu-latest
    timeout-minutes: 45

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install training deps
        run: |
          python -m pip install -U pip
          pip install -r requirements-train.txt

      - name: Check dataset presence (docs/exports/velib.parquet)
        shell: bash
        run: |
          if [ ! -f docs/exports/velib.parquet ]; then
            echo "Dataset manquant: docs/exports/velib.parquet (lance d'abord velib-ingest)"; exit 1;
          fi
          echo "=== Dataset info ==="
          ls -lh docs/exports | sed 's/^/ - /'
          python - <<'PY'
          import pandas as pd
          df = pd.read_parquet('docs/exports/velib.parquet')
          print("[train] rows:", len(df), "stations:", df['stationcode'].nunique())
          print("[train] timespan:", df['tbin_utc'].min(), "->", df['tbin_utc'].max())
          PY

      - name: Train LGBM (T+60) and verify model file
        shell: bash
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: |
          set -euxo pipefail
          echo "PWD: $(pwd)"; ls -la

          # Entraîner (aucun skip)
          python - <<'PY'
          from src.forecast import train, _print_dataset_span
          _print_dataset_span()  # log min/max
          out = train(horizon_minutes=60, lookback_days=30)
          print("[train] OUT:", out)
          PY

          echo "=== After training, list models dir ==="
          ls -lah models || true

          echo "=== Check model presence ==="
          test -f models/lgb_nbvelos_T+60min.joblib || { echo "[CI] modèle introuvable après entraînement"; exit 1; }

      - name: Upload model bundle
        uses: actions/upload-artifact@v4
        with:
          name: model-lgbm-T+60min
          path: models/lgb_nbvelos_T+60min.joblib
          retention-days: 14