name: velib-train

on:
  schedule:
    # Entraînement quotidien à 02:17 UTC
    - cron: "17 2 * * *"
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: velib-train
  cancel-in-progress: true

jobs:
  train_daily:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install training deps
        run: |
          python -m pip install -U pip
          pip install -r requirements-train.txt

      - name: Check dataset presence (docs/exports/velib.parquet)
        shell: bash
        run: |
          if [ ! -f docs/exports/velib.parquet ]; then
            echo "Dataset manquant: docs/exports/velib.parquet (lance d'abord velib-ingest)"; exit 1;
          fi
          echo "=== Dataset info ==="
          ls -lh docs/exports | sed 's/^/ - /'
          python - <<'PY'
          import pandas as pd
          df = pd.read_parquet('docs/exports/velib.parquet')
          print("[train] rows:", len(df), "stations:", df['stationcode'].nunique())
          print("[train] timespan:", df['tbin_utc'].min(), "->", df['tbin_utc'].max())
          PY

      - name: Train LightGBM (T+60min)
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: |
          python - <<'PY'
          from src.forecast import train, _print_dataset_span
          import pandas as pd
          tmin,tmax,, = _print_dataset_span()
          if pd.Timestamp(tmax) - pd.Timestamp(tmin) < pd.Timedelta(hours=2):
              print("[train] Skip: not enough timespan yet (need > ~2h).")
          else:
              train(horizon_minutes=60, lookback_days=30)
          PY

      - name: Upload model bundle
        uses: actions/upload-artifact@v4
        with:
          name: model-lgbm-T+60min
          path: models/lgb_nbvelos_T+60min.joblib
          retention-days: 14

      # (Optionnel) Commit du modèle directement dans le repo
      # - name: Commit model if changed
      #   run: |
      #     set -euxo pipefail
      #     git config user.name  "github-actions"
      #     git config user.email "actions@users.noreply.github.com"
      #     git add models/lgb_nbvelos_T+60min.joblib || true
      #     if git diff --cached --quiet; then
      #       echo "Nothing to commit."
      #     else
      #       git commit -m "ci(train): update LGBM model T+60min"
      #       git push
      #     fi
